# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecthub', '0002_project_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_review', models.CharField(max_length=60)),
            ],
        ),
    ]
