# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecthub', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_bio', models.CharField(max_length=60)),
                ('profile_contact', models.CharField(max_length=60)),
                ('profile_location', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
            ],
        ),
    ]
