# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecthub', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_contact',
            field=models.IntegerField(),
        ),
    ]
